.SILENT: all
CC=gcc
all: build
build: all_8oc_vec_ptr_87.S hl98_httpreq_func_89.S final_test_gen.S
	$(CC) all_8oc_vec_ptr_87.S hl98_httpreq_func_89.S final_test_gen.S -o zipfilegen.out
clean: 
	@rm -rf *.out